# Generated by Django 4.1.5 on 2023-09-09 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_resettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 10, 48, 39, 599079, tzinfo=datetime.timezone.utc)),
        ),
    ]
