# Generated by Django 4.1.5 on 2023-07-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
    ]
