# Generated by Django 4.1.5 on 2023-08-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0005_scheduledtaskargs'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
