# Generated by Django 4.1.5 on 2023-08-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0007_scheduledtaskargs_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtaskargs',
            name='request_user',
            field=models.IntegerField(),
        ),
    ]
