# Generated by Django 4.1.5 on 2023-08-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0008_alter_scheduledtaskargs_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtaskargs',
            name='request_user',
        ),
    ]
