# Generated by Django 4.1.5 on 2023-08-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0011_remove_feeds_categories_feeds_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtaskargs',
            name='feed_user',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
