# Generated by Django 4.1.5 on 2023-08-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0012_scheduledtaskargs_feed_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtaskargs',
            name='feed_user',
        ),
    ]
